'use client';

import 'katex/dist/katex.min.css';
import { renderEquations, containsMath } from '@/lib/equation-renderer';

interface EquationTextProps {
  text: string;
  className?: string;
}

/**
 * Renders inline text with KaTeX math support. Recognises `$...$`,
 * `$$...$$`, and plain-text shorthand (x^2, sqrt(), frac()). Plain
 * segments are HTML-escaped by `renderEquations` before injection.
 */
export function EquationText({ text, className }: EquationTextProps) {
  if (!containsMath(text)) {
    return <span className={className}>{text}</span>;
  }

  const html = renderEquations(text);

  return (
    <span
      className={className}
      // KaTeX output is generated by the library — not user-supplied HTML
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}
